import type { Metadata } from "next";

import "./globals.css";
import { Poppins } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const textFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= {`${textFont.className} min-h-full relative`}>
        {children}
      </body>
    </html>
  );
}
